#!/bin/bash
# shellcheck disable=2155,2002

# Set the input and output filenames
input_file="$1"
output_file="${input_file%.*}.tex"

# bac md file
input_file_tmp="$(mktemp)"
cp -f "$input_file" "$input_file_tmp"
input_file="$input_file_tmp"

main(){
  if [ -f "$input_file" ]; then
    _md_init

    pandoc "$input_file" -o "$output_file"
    if [ $? -eq 0 ];then
      _delete "hypertarget" "tightlist"
      _change "\\\section@\\\chapter" "\\\subsection@\\\section" "\\\subsubsection@\\\subsection" "\\\subsubsubsection@\\\subsubsection"
      _change "\\\label{[^}].*}@"
      _compo
      _insert_at_top
    fi
  else
    # Display an error message if the input file does not exist
    echo "Error: Input file not found!"
  fi
}

_md_init(){
  # after compo add new line, because pandoc
  # not give me all figure code of includegraphics
  sed -i 's@^--- *compo *= *[0-9] *$@&\n\n@' "$input_file_tmp"
}


_compo(){
  # why if compo text after image content \
  # how i can hadle gredy for only \begin{figure}
  local tmp="$(mktemp)"
  cat "$output_file" | sed ':a;N;$!ba;s#\n#@@@#g' |
  sed 's/--- *compo *= *\([0-9]\) *@@@\([^\]*\).\{47\}\([^}]*\).\{12\}.\([^}]*\).\{16\}/@@@\\compo\[0.\1]{\n\2\n}{\n\\includegraphics[height=\\textwidth,width=\\textwidth]{\3}\n}{\4}/g'  |
  sed 's#@@@#\n#g' > "$tmp"
  cat "$tmp" > "$output_file"
}


_change(){
  args=""
  for arg in "$@"; do
    args="${args};s@${arg}@"
  done
  args="s@${args:3}"
  echo -e "sed -i $args"
  sed -i "$args" "$output_file"
}

_delete(){
  args=""
  for arg in "$@"; do
    args="$args; /$arg/d"
  done
  args="${args:2}"
  echo -e "sed -i $args"
  sed -i "$args" "$output_file"
}

_insert_at_top(){
sed -i '1i\
%% the page should recalculate\
%% or create an tex scipt to calcle automaitic\
%% Adjust expace for the section and subsection and chapter\
% \pagestyle{monstyle}setcounter{page}{5}\
\\chapter{Introduction}\
\\vspace{2cm}\
\\section{Historique}\
\\subsection{1950}\
' "$output_file"
}

main
