#!/bin/bash

# Set the input and output filenames
input_file="$1"
output_file="${input_file%.*}.tex"

main(){
  # Check if the input file exists
  if [ -f "$input_file" ]; then
    # Convert the input file to a LaTeX file

    pandoc "$input_file" -o "$output_file"
    if [ $? -eq 0 ];then
      _delete "hypertarget" "tightlist"
      _change "\\\section@\\\chapter" "\\\subsection@\\\section" "\\\subsubsection@\\\subsection" "\\\subsubsubsection@\\\subsubsection"
      _change "\\\includegraphics@\\\includegraphics\[height=\\\textwidth,width=\\\textwidth\]"
      _change "\\\label{[^}].*}@"
      _insert_at_top
    fi
  else
    # Display an error message if the input file does not exist
    echo "Error: Input file not found!"
  fi
}

_change(){
  args=""
  for arg in "$@"; do
    args="${args};s@${arg}@"
  done
  args="s@${args:3}"
  echo -e "sed -i $args"
  sed -i "$args" "$output_file"
}

_delete(){
  args=""
  for arg in "$@"; do
    args="$args; /$arg/d"
  done
  args="${args:2}"
  echo -e "sed -i $args"
  sed -i "$args" "$output_file"
}

_insert_at_top(){
sed -i '1i\
%% the page should recalculate\
%% or create an tex scipt to calcle automaitic\
%% Adjust expace for the section and subsection and chapter\
\\pagestyle{monstyle}\setcounter{page}{1}\
\\chapter{Introduction}\
\\vspace{2cm}\
\\section{Historique}\
\\vspace{-1cm}\
\\subsection{1950}\
\\vspace{-1cm}' "$output_file"
}
main
